name: Folder Changes

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Find changed folders
        id: find_changed_folders
        run: |
          echo "::set-output name=changed_folders::$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | cut -d/ -f1 | sort -u)"
      
      - name: Set folder names
        id: set_folder_names
        run: |
          echo "FOLDER_NAMES=${{ steps.find_changed_folders.outputs.changed_folders }}" >> $GITHUB_ENV

      - name: Pass folder names to CodePipeline
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: 'AKIAQVE27LPWLWOETLIL'
          aws-secret-access-key: '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'
          aws-region: 'us-east-1'
          args: codepipeline start-pipeline-execution --name Folder-changes-testing-pipeline --query 'pipelineExecutionId' --output text
        env:
            FOLDER_NAMES: ${{ steps.set_folder_names.outputs.FOLDER_NAMES }}
